apiVersion: apps/v1
kind: Deployment
metadata:
  name: o3as-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: o3as-api
  template:
    metadata:
      labels:
        name: o3as-api
    spec:
      nodeName: vnode-1.localdomain
      #nodeSelector:
      #  node-role.kubernetes.io/master: ''
      containers:
      - name: o3as-api
        image: synergyimk/o3as:test
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "2100m"
          limits:
            memory: "2.5Gi"
            cpu: "2300m"
        ports:
        - containerPort: 5005
          name: port0
        #tolerations:
        #- key: node-role.kubernetes.io/master
        #  effect: NoSchedule
        env:
        - name: O3AS_DATA_BASEPATH
          value: /mnt/o3as-data/Skimmed
        - name: O3AS_TIMEOUT
          value: "600"
        #  valueFrom: 
        #    secretKeyRef:
        #      name: jupyter-pass
        #      key: jpassword
        volumeMounts:
        - mountPath: /mnt/o3as-data
          name: o3as-data
      volumes:
      - name: o3as-data
        hostPath:
          path: /mnt/o3as-data
          type: Directory

# Service
---
kind: Service
apiVersion: v1
metadata:
  name: o3as-service
spec:
  selector:
    name: o3as-api
  ports:
    - protocol: TCP
      name: http2
      port: 5005
      nodePort: 30505
  type: NodePort
